### ISSUE TITLE
config.yml Monitor.Password is null error

### ISSUE THREAD

**Issue by Gedatang** [Navid2zp/citus-failover#12]
If config.yml  Monitor.Password is null,   The following error will be reported

2022/08/03 12:57:37 Settings initialized ...
2022/08/03 12:57:37 Starting api on port 3002 ...
panic: pq: database "autoctl_node" does not exist

goroutine 1 [running]:
github.com/Navid2zp/citus-failover/core.openMonitoringConnection()
	/home/runner/work/citus-failover/citus-failover/core/db.go:44 +0x249
github.com/Navid2zp/citus-failover/core.InitMonitor()
	/home/runner/work/citus-failover/citus-failover/core/init.go:17 +0x25
main.main()
	/home/runner/work/citus-failover/citus-failover/main.go:22 +0x10c

**Comment by Navid2zp** [comment]
Hello @Gedatang,

Thanks for opening the issue.

As I understand, citus-failover failed to find the database to connect to. Password should not play a role here.
Can you test to see if the database is accessible using the information you provided to citus-failover?
